spring:
  application:
    name: service-actors
  config:
    activate:
      on-profile: actors

sede:
  id: A
  nombre: "Sede A"

# Conexión al GC (para suscribirse a los tópicos)
gc:
  host: "sede-a.local"

zmq:
  pub:
    dev:
      port: 7002     # topic Devolucion publicado por GC A
    ren:
      port: 7003     # topic Renovacion publicado por GC A

# Conexión al GA (para enviar REQ/REP desde los Actores)
ga:
  host: "sede-a.local"
  rep:
    port: 9020
  timeoutMs: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
