spring:
  application:
    name: service-actors
  config:
    activate:
      on-profile: actors

sede:
  id: B
  nombre: "Sede B"

gc:
  host: "sede-b.local"

zmq:
  pub:
    dev:
      port: 7102     # GC B publica Devolucion aquí
    ren:
      port: 7103     # GC B publica Renovacion aquí

ga:
  host: "sede-b.local"
  rep:
    port: 9120
  timeoutMs: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
